fixes

diff --git a/xforce-ansible-challenge/ansible-ad-hoc-challenge/check-shell b/xforce-ansible-challenge/ansible-ad-hoc-challenge/check-shell
--- a/xforce-ansible-challenge/ansible-ad-hoc-challenge/check-shell
+++ b/xforce-ansible-challenge/ansible-ad-hoc-challenge/check-shell
@@ -1,4 +1,16 @@
 #!/bin/bash
-echo "Checking the solution of the challenge"
-echo "DIAG: instruqt challenge not ready, please check later"
-exit 1
+#echo "Checking the solution of the challenge"
+#echo "DIAG: instruqt challenge not ready, please check later"
+#exit 1
+
+#if [ -f "${USERFILE}" ]
+#then
+# 	echo "${USERFILE} found."
+#else
+#   echo "DIAG: ${USERFILE} not found. Please read instructions."
+#	exit 1
+#fi
+
+grep ^devops /etc/group -q
+RETVAL=$?
+[ $RETVAL -ne 0 ]  && { echo "DIAG: group does not exist on ${HOSTNAME}"; exit 1; }
